### ISSUE TITLE
How to Add performance : manage the AddDirtyRect in WritableBitmap

### ISSUE THREAD

**Issue by polipo** [reneschulte/WriteableBitmapEx#31]
**For Improve performance** when drawing multiple forms in same time you can getBitmapContext and use it for draw, there's a little bottleneck when the BitmapContext disposed this add automatically AddDirtyRect with full bitmap size.
 
The *correct solution* will be automatically adds AddDirtyRects for refresh only the changed bitmap portions. 

A temporaney workaround is get the Context in ReadOnly mode and when you finish (before dispose) add manually the AddDirtyRect of the desiderated size.

Example:
              ```
                         using (BitmapContext ctx = wBitmap.GetBitmapContext(ReadWriteMode.ReadOnly))
                         {
                    ctx.WriteableBitmap.DrawLine((int)pPrec.X, (int)pPrec.Y, (int)pNext.X, (int)pNext.Y, colorPlot.ToArgb());

                        ctx.WriteableBitmap.AddDirtyRect(new Int32Rect((int)pPrec.X, 0, (int)pNext.X, (int)ctx.WriteableBitmap.Height));
                
                      } //when exit  the lib call only Unlock() in ReadOnly mode;

```

**Comment by teichgraf** [comment]
Thanks. If you have a general purpose idea how to handle it the best, a Pull Request would be welcomed. :-)

**Comment by polipo** [comment]
For now is an only an idea .. to record/add the modified rects in Bitmap Context.. on my simple test this can be an improvement of 5/10%
