### ISSUE TITLE
CopyPixels() Hanging

### ISSUE THREAD

**Issue by CDarbonne** [reneschulte/WriteableBitmapEx#43]
So I'm trying to implement a function that modifies a bitmaps pixels. It was originally implemented using unsafe code/pointers and worked fine. We are now trying to convert it into a safe variation of the function. The piece that is snagging me currently is replacing:

`var pixels = context.Pixels;`

to

```
pixels = new int[context.Width * context.Height];
context.WriteableBitmap.CopyPixels(pixels, context.WriteableBitmap.BackBufferStride, 0);
```

For some reason, CopyPixels just hangs when it gets to that line. Im assuming there has to be some kind of infinite loop in there causing the issue, but not 100% sure. I noticed the api doc said that the bitmap is locked when in the BitmapContext and figured maybe it needed to be unlocked in order to work. I tried calling `context.WriteableBitmap.Unlock();` first to see but get the message "Cannot perform this action on an unlocked bitmap", so maybe its not locked after all? 

I can call CopyPixels successfully on the original WriteableBitmap just before going into the context so I know its not an issue of the bitmap not being good, and like I said before, the implementation works if just the original line of code with `context.Pixels` is used, so I am at a loss for what could be the issue. 

Any help or direction would be greatly appreciated!

**Comment by reneschulte** [comment]
I assume you are using WPF? If so, indeed you need to use the BitmapContext since it locks and unlocks for optimized speed. Take a look at the samples. This should work: 
```
// Wrap updates in a GetContext call, to prevent invalidation and nested locking/unlocking during this block
using (var context = writeableBmp.GetBitmapContext())
{
    var pixels = new int[context.Width * context.Height];
    context.WriteableBitmap.CopyPixels(pixels, context.WriteableBitmap.BackBufferStride, 0);
}
```

**Comment by gmgallo** [comment]
I can confirm that CopyPixels() hangs with the code exactly as rene shows above. The code runs in the UI thread. Something enters in a dead lock in there.

**Comment by reneschulte** [comment]
To be clear @gmgallo are you saying even with the using() which calls Unlock under the hood, the issue is still there? 
If you test code, it would be great to access to debug it.

**Comment by gmgallo** [comment]
Hi Rene,

Yes, enclosed inside a using() {} exactly as you show in your answer.

I’ll prepare a strip down sample of my code and upload it later.
It is a desktop WPF app targeting .NET framework 4.6  x86.

Best regards,

Guillermo Gallo
Global Geo Supplies, Inc.
VP Business Development
Office:   +1 303 792 5157
Mobile: +1 303 808 1919
Mail: guillermo@ggsnet.com<mailto:guillermo@ggsnet.com>


[cid:image002.png@01D398DB.DE9605F0]
6150 Puma Point
 Lone Tree CO 80124 – USA
 www.G2Airborne.com<http://www.g2airborne.com/>

**Comment by gmgallo** [comment]
Here is a test bed that shows the problem. You need to uncomment the offending line. 
[Testbed.zip](https://github.com/reneschulte/WriteableBitmapEx/files/3214387/Testbed.zip)

**Comment by reneschulte** [comment]
One issue that sticks out right away. You are recreating the WB inside the using. You can't do that. 
![image](https://user-images.githubusercontent.com/7439129/58335362-bcfa3900-7e41-11e9-8cc0-8acea9ffb37d.png)

**Comment by reneschulte** [comment]
Alright, I was wrong. DON'T use CopyPixels in the Context. 
CopyPixels lock the buffer internally as well and since in the context it's already locked you end up with a deadlock. 
This works: 
![image](https://user-images.githubusercontent.com/7439129/58336117-6261dc80-7e43-11e9-931a-4a9342deafd9.png)

**Comment by reneschulte** [comment]
If you wanna copy pixels from one WB to another WB, you want to use the Blit(...) methods BTW. 
Take a look at the sample for Blit.

**Comment by gmgallo** [comment]
Ops!, I overlooked the dual bitmap creation.  Thanks for the clarifications.

Guillermo

**Comment by gmgallo** [comment]
I noticed another error in the sample code above. In my system CopyPixels() threw an out of bounds exception. The problem is the buffer size calculation. It must be done with PixelHeight and PixelWidth not Height and Width:
![image](https://user-images.githubusercontent.com/11802515/58376016-c9ec5a80-7f1d-11e9-83b6-7ced7e8e1fa4.png)
