### ISSUE TITLE
DrawLineDotted throws AccessViolationException on v1.6.3

### ISSUE THREAD

**Issue by diontools** [reneschulte/WriteableBitmapEx#50]
This issue is different pattern from #46.

reproducing code:
```csharp
var wb = BitmapFactory.New(500, 500);
wb.DrawLineDotted(0, 0, 100, 0, 1, 1, Colors.Red);
```

**Comment by reneschulte** [comment]
Good catch. Thanks. Fixed in latest commit and merged into master with 5f8639889932d09dab0ce16575c2e7ddafcf6ab9
