### ISSUE TITLE
WPF: Safe mode

### ISSUE THREAD

**Issue by paulushub** [reneschulte/WriteableBitmapEx#52]
Is there a way to compile a safe mode version for WPF (Similar to the SilverLight)?

**Comment by reneschulte** [comment]
There's surely a way but it's not designed for that. The WPF version uses unsafe code for direct memory access to get the maximum performance which has always been the top priority for this library. 

If you poke around in the code and see the Silverlight and UWP portions to modify the WPF code, I'm sure you can find a way to compile it without unsafe code for WPF.
