### ISSUE TITLE
Feature Request: arc drawing

### ISSUE THREAD

**Issue by hillin** [reneschulte/WriteableBitmapEx#54]
It would be great if we can have [`DrawArc`](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.graphics.drawarc?view=netcore-3.1) like methods.

**Comment by reneschulte** [comment]
You might be able to work around this by drawing a filled ellipse and then masking out the parts you don't want to have with DrawPolygon.

**Comment by hillin** [comment]
Yeah and we can also approach it with a bezier curve or a cardinal spline. There are all sorts of workarounds, but we are call coming for performance and convenience aren't we ;)

**Comment by reneschulte** [comment]
Not sure I will have much time for this. If you have a PR with a proposal that would be great and help a lot.
