### ISSUE TITLE
Cross thread bitmapContext

### ISSUE THREAD

**Issue by zives** [reneschulte/WriteableBitmapEx#55]
1. I create a writeablebitmap in the UI thread.
2. For some huge computations on this bitmap I decide to pass the bitmapcontext to a new thread with `GetBitmapContext()`
3. I call SetPixel in this other thread and I get
![image](https://user-images.githubusercontent.com/2728729/79139285-52821c80-7db6-11ea-8661-be73bde8b83d.png)

The reason is that a new bitmapcontext instance is created in each extension method, and inside :
` public BitmapContext(WriteableBitmap writeableBitmap, ReadWriteMode mode)
        {
            _writeableBitmap = writeableBitmap;
            _mode = mode;

            _pixelWidth = _writeableBitmap.PixelWidth;`

`.PixelWidth` raise the exception.

I have already the context, so these properties should not be called

**Comment by reneschulte** [comment]
The SetPixel is not meant to be used in a background thread nor for mass pixel manipulation in general. It's way too slow setting every single pixel with a call. You can implement a fast way yourselves: see the BitmapConext.CopyPixels method on how to access the pixels in the right order, then look at the SetPixel method.
