### ISSUE TITLE
package for VsCode?

### ISSUE THREAD

**Issue by pkTux** [reneschulte/WriteableBitmapEx#57]
Im a bit of a newb to C# programming & i'm curious if its worth using WriteableBitmapEX as some videos suggest. However, I dont see it packaged for VScode, just Visual studio. Would anyone be able to package it? or is it just plug & play if I grab the correct Folder from the repo?

**Comment by flabbet** [comment]
WriteableBitmapEx is a library available on NuGet https://www.nuget.org/packages/WriteableBitmapEx/, you can install it to your project in CLI in VsCode, it's not an editor extension.
