### ISSUE TITLE
DrawPolyline seems slow for large amount of ink

### ISSUE THREAD

**Issue by cghersi** [reneschulte/WriteableBitmapEx#58]
I am successfully using your library in my UWP project.
I am using it specifically to draw a large amount of ink into a WriteableBitmap that I need to place as Source of an Image control.
I use DrawPolyline() to draw each single ink stroke, but apparently it is a little bit slow (for 900 strokes it takes 4 seconds...).
Is there a faster method?

**Comment by reneschulte** [comment]
Yes. Don't use this library for such things in UWP. There's a faster way.

**Comment by cghersi** [comment]
Thanks, could you please point me to the faster way?

**Comment by cghersi** [comment]
OK thanks! Do you happen to have a working example of the usage of the Win2D primitives for this use case?

**Comment by reneschulte** [comment]
Nope, but I'm sure you can something similar in the official samples there and adapt it.
