### ISSUE TITLE
Strong Name the Assembly

### ISSUE THREAD

**Issue by leonbohmann** [reneschulte/WriteableBitmapEx#59]
Hi Rene,

is it possible to include a strong name for the .net-Assemblies?

I rely on strong names for the integrity of my application and that would enable me to use your library!
Thanks a lot!

**Comment by reneschulte** [comment]
Hi @leonbohmann 

Good call. I just enabled that for the WPF and UWP versions (which I still maintain). 
I also pushed a new package to Nuget. Hope this helps.
