### ISSUE TITLE
InvalidOperationException thrown when trying to get a read-only BitmapContext on a frozen WriteableBitmap

### ISSUE THREAD

**Issue by CyberBotX** [reneschulte/WriteableBitmapEx#60]
If I attempt to do anything in WriteableBitmapEx that attempts to get a read-only BitmapContext on a WriteableBitmap that has been frozen by the `Freeze()` method (such as using the `Blit()` method), an InvalidOperationException is thrown from WPF's `System.Windows.Freezeable.WritePreamble()`, called in WriteableBitmap's `TryLock()` method, called in WriteableBitmap's `Lock()` method, which is called in WriteableBitmapEx here: https://github.com/reneschulte/WriteableBitmapEx/blob/aad837358b70a56af95c230e586a7d06638ebee5/Source/WriteableBitmapEx/BitmapContext.cs#L129-L131

I know that the concept of freezing a WriteableBitmap might not make much sense, but I am trying to use a frozen WriteableBitmap because of threading issues (if not frozen, I get an exception saying that the WriteableBitmap was being accessed on a different thread than it was originally created on), and I assumed that a read-only BitmapContext would let me use a frozen WriteableBitmap.

**Comment by reneschulte** [comment]
You are right. If you Release the BitmapContext like at the end of an using statement it will be unlocked. 
Typically there are other ways around this when having to use the WB in a different thread. Can you describe the scenario a little bit more in detail and what you are trying to achieve?

**Comment by CyberBotX** [comment]
So I create a WB that I intend to modify in the UI thread. Later within a separate task (through `Task.Run()`), I make some WBs that I freeze because I want to eventually blit them to the first WB, after the task has finished (I would do it in the task but WPF won't allow that). I've since changed my process for this so I just create the WBs at the time of doing the blit instead of beforehand, but I do not know how much of a performance hit this is causing for my scenario, if any.
