### ISSUE TITLE
System.AccessViolationException on Blit

### ISSUE THREAD

**Issue by MaxDeBy** [reneschulte/WriteableBitmapEx#61]
I'm getting a System.AccessViolationException when I try to use the Blit extension method, but I don't know why. 
I don't know what info would be required here, so I'll just give the meta on the images I'm trying to combine.
Dest:
- Width: 256
- Height: 192

DestRect:
- Width: 111
- Height: 191
- X: 76
- Y: 1

Source:
- Width: 111
- Height: 191

SourceRect:
- Width: 111
- Height: 191
- X: 0
- Y: 0

**Comment by mmedi005** [comment]
I'm getting this on rotate with a tif at 600 DPI, anyone know why?

**Comment by reneschulte** [comment]
Should be fixed by now.
