### ISSUE TITLE
drawString implementation link is not available any more

### ISSUE THREAD

**Issue by tbscer** [reneschulte/WriteableBitmapEx#63]
hi

I just follow the link of drawString implementation, but it guide me to nowhere

can you pls fix it?

thx

**Comment by reneschulte** [comment]
Thanks. Fixed. 
https://archive.codeplex.com/?p=writeablebitmapex

**Comment by tbscer** [comment]
And also, when i create a bmp, with size of 5000x5000, it will crash with function of DrawLine.

I read your master piece, and found it was due to data overflow

```
                int index = x1s;
                int indexBaseValue = y1 * pixelWidth;

                // Walk the line!
                var inc = (pixelWidth << PRECISION_SHIFT) + incx;
                for (int y = y1; y <= y2; ++y)
                {
                    pixels[indexBaseValue + (index >> PRECISION_SHIFT)] = color;
                    index += inc;
                }
```
the left shift operation caused that. Pls check, I just modified to to work as that:
`
                int index = x1s >> PRECISION_SHIFT;
                int indexBaseValue = y1 * pixelWidth;

                // Walk the line!
                var inc = ((pixelWidth << PRECISION_SHIFT) + incx) >> PRECISION_SHIFT;
                for (int y = y1; y <= y2; ++y)
                {
                    pixels[indexBaseValue + (index)] = color;
                    index += inc;
                }
`

**Comment by reneschulte** [comment]
Hi @tbscer great find. Your error description and fix makes sense (doing a quick glance at the code in the morning).
Would you mind submitting a Pull Request with these changes included?

**Comment by Mostlypyjamas** [comment]
Sadly even the codeplex archive has now shutdown - does anyone have a link to the DrawString discussion?

**Comment by reneschulte** [comment]
Unfortunately not but seems some folks were actually able to archive it. 
https://www.reddit.com/r/DataHoarder/comments/ngz26w/codeplex_archive_will_shut_down_please_help_me/

**Comment by diontools** [comment]
Internet Archive links:
https://web.archive.org/web/20171225021604mp_/https://writeablebitmapex.codeplex.com/discussions/579148
https://web.archive.org/web/20210629143745/https://archive.codeplex.com/?p=fastwpfgrid
