### ISSUE TITLE
Fill with Alpha doesnt affect

### ISSUE THREAD

**Issue by polipo** [reneschulte/WriteableBitmapEx#65]
The FillRectangle with a color with alpha channel != 255 doesn't affect the filled rectangle, I will aspect to drawing a Rectangle with Alpha channel (low trasparency) but it draw always alpha like 255

**Comment by reneschulte** [comment]
Note that WriteableBitmap uses pre-multiplied alpha.

**Comment by polipo** [comment]
There's a way to fill/draw a WritableBitmap with a sort of trasparency?

**Comment by polipo** [comment]
This can be an example of Blend a sort of transparency

public static void FillRectangleBlend(this BitmapContext context, int x1, int y1, int x2, int y2, System.Drawing.Color color)
        {
            var w = context.Width;
            var h = context.Height;
            var pixels = context.Pixels;

            // Check boundaries
            if ((x1 < 0 && x2 < 0) || (y1 < 0 && y2 < 0)
             || (x1 >= w && x2 >= w) || (y1 >= h && y2 >= h))
            {
                return;
            }

            // Clamp boundaries
            if (x1 < 0) { x1 = 0; }
            if (y1 < 0) { y1 = 0; }
            if (x2 < 0) { x2 = 0; }
            if (y2 < 0) { y2 = 0; }
            if (x1 >= w) { x1 = w - 1; }
            if (y1 >= h) { y1 = h - 1; }
            if (x2 >= w) { x2 = w - 1; }
            if (y2 >= h) { y2 = h - 1; }

            byte oneOverAlpha = (byte)(255 - color.A);

            unchecked
            {
                for (int y = y1; y <= y2; y++)
                {
                    for (int i = y * w + x1; i <= y * w + x2; i++)
                    {
                        int c = pixels[i];
                        int r = ((byte)(c >> 16) * oneOverAlpha + color.R * color.A) >> 8;
                        int g = ((byte)(c >> 8) * oneOverAlpha + color.G * color.A) >> 8;
                        int b = ((byte)(c >> 0) * oneOverAlpha + color.B * color.A) >> 8;

                        pixels[i] = 255 << 24 | r << 16 | g << 8 | b;


                    }
                }

            }
        }



        public static void FillRectangleBlend(this WriteableBitmap bmp, int x1, int y1, int x2, int y2, System.Drawing.Color color)
        {
            using (BitmapContext context = bmp.GetBitmapContext())
            {
                FillRectangleBlend(context, x1, y1, x2, y2, color);
            }
        }

**Comment by reneschulte** [comment]
> 
> 
> There's a way to fill/draw a WritableBitmap with a sort of trasparency?

Yes, it actually does already and there's even a sample showing that called WriteableBitmapExFillSample. See screenshot below with the two overlapped rectangles. 

Sorry, missed your point in my earlier reply. Basically make sure to set the last method parameter `doAlphaBlend` to `true`.

This is the relevant code from the sample. Not the second call's last parameter: 

```
// Fill Rectangle
writeableBmp.FillRectangle(rand.Next(2*w3, 2*w3 + w6), rand.Next(2*h3, 2*h3 + h6),
                            rand.Next(2*w3 + w6, w), rand.Next(2*h3 + h6, h), GetRandomColor());
// Fill another rectangle with alpha blending
writeableBmp.FillRectangle(rand.Next(2 * w3, 2 * w3 + w6), rand.Next(2 * h3, 2 * h3 + h6),
        rand.Next(2 * w3 + w6, w), rand.Next(2 * h3 + h6, h), GetRandomColor(), true);
```

![image](https://user-images.githubusercontent.com/7439129/108380803-7ea4d000-7207-11eb-8b31-0024710b95bb.png)
