### ISSUE TITLE
Parallelism on drawing geometry elements

### ISSUE THREAD

**Issue by afcsoft** [reneschulte/WriteableBitmapEx#66]
When i try to draw on bitmap in parallel, i got this exception: 
_The calling thread cannot access this object because a different thread owns it_

Code:

```
                Parallel.For(0, 100, i =>
                  {                      

         WriteableBitmapExtensions.FillEllipseCentered(buffer, 0, 0, 100, 100, System.Windows.Media.Color.FromRgb(125, 125, 125));

                                         
                  });
```

Is it possible draw geometry elements in parallel like what i tried using WriteableBitmapEx?

**Comment by reneschulte** [comment]
Hi! You can not access the WriteableBitmap on a different thread than it was created. 
BUT, you can fill a pixels array in a background thread and then assign this via the BitmapContext.Pixels property or by using the BlockCopy methods.
