### ISSUE TITLE
Rendering problem when maximizing the window.

### ISSUE THREAD

**Issue by son11592** [reneschulte/WriteableBitmapEx#67]
Hi all,

This project is awesome, I have tried it in my product. But there is a minor issue that the layout is buggy when rendering in the maximized window (See the pictures below). I don't why it happened. Any ideas?

The normal state of the window, the rendering is quite good
![image](https://user-images.githubusercontent.com/4739616/113270736-03edcb00-9304-11eb-8168-855f5d6796ae.png)

After maximizing the window, the text is buggy. I have no idea!!
![image](https://user-images.githubusercontent.com/4739616/113270789-0f40f680-9304-11eb-8fd8-97052a268538.png)

Any idea in this case? Thanks.

**Comment by reneschulte** [comment]
Looks good to me. Not sure.
