### ISSUE TITLE
System.AccessViolationException in DrawLine with Fix

### ISSUE THREAD

**Issue by Sockenfresser** [reneschulte/WriteableBitmapEx#68]
In public static void DrawLine(BitmapContext context, int pixelWidth, int pixelHeight, int x1, int y1, int x2, int y2, int color, Rect? clipRect = null) a System.AccessViolationException is thrown. It seems that there is an overflow in the index variable. Simply make the overflowing index a 64 bit integer.

Original Code

```csharp
                int index = x1s;
                int indexBaseValue = y1 * pixelWidth;

                // Walk the line!
                var inc = (pixelWidth << PRECISION_SHIFT) + incx;
                for (int y = y1; y <= y2; ++y)
                {
                    pixels[indexBaseValue + (index >> PRECISION_SHIFT)] = color;
                    index += inc;
                }
```
Fix

```csharp
                long index = x1s;
                int indexBaseValue = y1 * pixelWidth;

                // Walk the line!
                var inc = (pixelWidth << PRECISION_SHIFT) + incx;
                for (int y = y1; y <= y2; ++y)
                {
                    pixels[indexBaseValue + (index >> PRECISION_SHIFT)] = color;
                    index += inc;
                }
```

**Comment by cwenger** [comment]
@reneschulte Do you know when this will be released to NuGet? Just ran into this exception with the current version.

**Comment by reneschulte** [comment]
@cwenger Just pushed a new package to NuGet containing this and a few more fixes.
https://www.nuget.org/packages/WriteableBitmapEx/1.6.8

**Comment by cwenger** [comment]
@reneschulte Works great, thanks for the package and the quick response!
