### ISSUE TITLE
Filled shape

### ISSUE THREAD

**Issue by laurentchougrani** [reneschulte/WriteableBitmapEx#72]
Hi all !
Nice nuget, very usefull !

I've been wondering for the "DrawTriangle" , "DrawQuad" etc.. functions. 
Would it be possible to pass a boolean argument for "Fill" or "stroke" as in
- all pixels inside the shape are colored the same way.
-  only the shape contour is colored.

Might seem like a specific question, yet i do really need it and see many applications for it (thus for other folks)

Thanks all.

**Comment by reneschulte** [comment]
Salut Laurent!
You can use the Fill* methods to draw the filling and then the DrawLine overloaded methods to overdraw the boundaries with different colors, dashed or dotted line, etc. Or simply FillQuad with color 1 and DrawQuad with color 2 for the outline.

**Comment by laurentchougrani** [comment]
Ohh yes!
Sorry my bad... didn't went through the whole listing of methods.
Thanks, it works fine.
Thanks again for the effort you put in that work, helps a lot.

**Comment by reneschulte** [comment]
You're welcome. Much success. 😊
