### ISSUE TITLE
Is it possible to use WriteableBitmapEx in Windows App Sdk (WinUI 3)

### ISSUE THREAD

**Issue by nikolayvpavlov** [reneschulte/WriteableBitmapEx#79]
At present, it seems that WriteableBitmapEx depends heavily on WPF.  Is it possible to use WriteableBitmapEx in Windows App Sdk (WinUI 3)?

**Comment by reneschulte** [comment]
No. WBX was written for WPF and similar frameworks back in the days. WinUI has AFAIK already a pretty fast graphics API for bitmap manipulation. I'd recommend to use that.
________________________________
From: Nikolay Pavlov ***@***.***>
Sent: Friday, October 28, 2022 13:24
To: reneschulte/WriteableBitmapEx
Cc: Subscribed
Subject: [reneschulte/WriteableBitmapEx] Is it possible to use WriteableBitmapEx in Windows App Sdk (WinUI 3) (Issue #79)


At present, it seems that WriteableBitmapEx depends heavily on WPF. Is it possible to use WriteableBitmapEx in Windows App Sdk (WinUI 3)?
