### ISSUE TITLE
when i use DrawLineAa the line is strange

### ISSUE THREAD

**Issue by moonfanslyj** [reneschulte/WriteableBitmapEx#82]
thanks for you work，WriteableBitmapEx is good

![image](https://user-images.githubusercontent.com/25874980/227157688-de2b8042-5dc7-4c78-91ca-b57ed72e8c0d.png)
this is my code
 writeableBmp.Clear(Colors.Transparent);
            using (var context = writeableBmp.GetBitmapContext())
            {
                for (int index = 0; index < itemsSource.Count; ++index)
                {
                    IPointArray pointArray = itemsSource[index];
                    int[] points = new int[pointArray.Points.Length * 2];
                    for (int z = 0; z < pointArray.Points.Length - 1; z++)
                    {
                        int x = (int)pointArray.Points[z].X;
                        int y = (int)pointArray.Points[z].Y;
                        int x1 = (int)pointArray.Points[z + 1].X;
                        int y1 = (int)pointArray.Points[z + 1].Y;
                        WriteableBitmapExtensions.DrawLineAa(context, context.Width, context.Height, x, y, x1, y1,pen,2);
                    }
                }
            }
 is there any way to solve this problem？

**Comment by reneschulte** [comment]
What's the problem actually? Please describe in more detail.

**Comment by moonfanslyj** [comment]
WriteableBitmapExtensions.DrawLineAa(context, context.Width, context.Height, x, y, x1, y1,pen,2);
strokeThickness set 2,there are many white dots in the middle of the line
the greater the value, the more obvious the more effective

**Comment by moonfanslyj** [comment]
![image](https://user-images.githubusercontent.com/25874980/227474519-62adf91b-d08c-475c-90e5-477daea682ca.png)
when i set strokeThickness  = 4 ,its more effective.
how to solve this ?

**Comment by moonfanslyj** [comment]
The source code has been posted on it. The main code is as some. Other code is business logic, and there will be no help.Or maybe you want the specific content of Points?
Anyway, thank you for your reply
I will try other solutions
